name: ESLint
on: [push, workflow_dispatch]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: plastikmensch/eslint-check-action@testing
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
        eslintFiles: "src"
        eslintConfig: ".eslintrc.json"
        eslintExt: "js"
